apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: sample-job-2
spec:
  image: flink:1.17
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "200m"
      cpu: 0.1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  job:
    jarURI: {{JOB_URI}}
    parallelism: 2
    upgradeMode: stateless